apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels: { app: portfolio-frontend }
spec:
  replicas: 2
  selector:
    matchLabels: { app: portfolio-frontend }
  template:
    metadata:
      labels: { app: portfolio-frontend }
    spec:
      containers:
        - name: web
          image: sachal-portfolio-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: "25m", memory: "32Mi" }
            limits: { cpu: "100m", memory: "128Mi" }
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend
  labels: { app: portfolio-frontend }
spec:
  type: LoadBalancer
  selector: { app: portfolio-frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
