apiVersion: v1
kind: Service
metadata:
  name: sachal-portfolio
  labels:
    app: sachal-portfolio
spec:
  type: ClusterIP
  selector:
    app: sachal-portfolio
  ports:
    - name: http
      port: 80
      targetPort: 8000
